
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                yy_size_t yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 40
#define YY_END_OF_BUFFER 41
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[159] =
    {   0,
        0,    0,   41,   39,   36,   38,   29,   39,   30,   31,
       25,   23,   20,   24,   28,   37,   17,   17,   17,   17,
       19,   22,   21,   22,    9,    9,   32,   33,    9,    9,
        9,    9,    9,    9,   34,   39,   35,   22,   26,    0,
        0,   12,    2,    1,    0,   13,   13,   14,    0,   17,
       17,   17,   17,    9,   12,   12,    9,    9,    9,    9,
        5,    9,    9,    9,    9,   27,    0,   12,   12,   10,
       15,   16,   17,   17,   17,   17,   17,   12,    9,    9,
        8,    9,    9,    9,    0,   12,   11,   17,   17,   17,
       17,   17,   17,    6,    9,    9,    9,    9,    0,   17,

       17,   17,   17,   17,   17,   17,    9,    9,    7,    0,
       17,   17,   17,   17,   17,   17,   17,   17,    4,    3,
        0,   17,   17,   17,   17,   17,   17,   17,   17,   17,
        0,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,    0,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,    0,   17,   18,   17,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    2,    1,    1,    1,    5,    1,    6,
        7,    8,    9,   10,   11,   12,   13,   14,   15,   16,
       17,   18,   19,   20,   21,   22,   23,    1,   24,   25,
       26,   27,    1,    1,   28,   28,   28,   28,   29,   28,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   31,   30,   30,
       32,    1,   33,    1,   34,    1,   35,   28,   36,   28,

       37,   38,   30,   39,   40,   30,   30,   41,   30,   42,
       43,   30,   30,   44,   45,   46,   47,   30,   48,   31,
       30,   30,   49,   50,   51,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[52] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    1,
        2,    3,    1,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    1,    1,    1,    1,    5,    6,    5,
        5,    1,    1,    7,    5,    5,    6,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    1,    1,
        1
    } ;

static yyconst flex_int16_t yy_base[210] =
    {   0,
        0,    0,  325,  663,  663,  663,  297,  316,  663,  663,
      663,  663,  663,  304,   23,   45,   49,   44,   62,   50,
      663,  291,  289,  287,    0,   91,  663,  663,  266,  264,
       17,  265,  243,  248,  663,  236,  663,  663,  663,  244,
       46,   86,  663,  663,   53,  226,   70,   92,  116,  112,
      113,  153,  163,    0,  174,    0,  178,    0,  210,  209,
        0,  199,  198,  199,  200,  663,  201,  183,    0,   56,
        0,    0,  172,  176,  179,  209,  181,    0,  169,  169,
        0,  155,  153,  158,  177,  224,    0,  185,  205,  225,
      227,  253,  233,    0,  150,  122,  112,  106,  122,  229,

      248,  251,  266,  267,  269,  271,   85,   80,    0,  100,
      272,  281,  282,  285,  287,  300,  326,  102,    0,    0,
       79,  321,  322,  323,  324,  327,  342,  345,  371,  366,
       74,  368,  369,  372,  384,  387,  390,  399,  400,  426,
      351,   74,  402,  421,    0,    0,    0,    0,    0,    0,
        0,   66,  422,   35,  423,    0,  663,  663,  460,  464,
      468,  471,  477,  480,  484,  488,  492,   50,  497,  500,
      504,  508,  512,  516,  520,  524,  528,  532,  536,  540,
      544,  548,  552,  556,  560,  564,  568,  572,  576,  580,
      584,  588,  592,  596,  600,  604,  608,  612,  616,  620,

      624,  628,  632,  636,  640,  644,  648,  652,  656
    } ;

static yyconst flex_int16_t yy_def[210] =
    {   0,
      158,    1,  158,  158,  158,  158,  158,  158,  158,  158,
      158,  158,  158,  158,  159,  158,  158,  160,  161,  161,
      158,  158,  158,  158,  162,  162,  158,  158,   26,  162,
      162,  162,  162,  162,  158,  158,  158,  158,  158,  158,
      159,  163,  158,  158,  164,   17,   17,  165,  158,  166,
      167,  158,   52,  162,  163,  168,   26,   26,  162,  162,
      162,  162,  162,  162,  162,  158,  158,  169,   55,  164,
       49,  170,  171,  172,  173,  158,  174,  168,  162,  162,
      162,  162,  162,  162,  158,  169,   86,  175,  176,  177,
      178,  158,   92,  162,  162,  162,  162,  162,  158,  179,

      180,  181,  182,  183,  184,  185,  162,  162,  162,  158,
      186,  187,  188,  189,  190,  191,  158,  117,  162,  162,
      158,  192,  193,  194,  195,  196,  197,  198,  158,  199,
      158,  200,  201,  202,  203,  204,  205,  206,  207,  158,
      140,  158,  208,  208,  144,  144,  144,  144,  144,  144,
      144,  144,  209,  158,  209,  155,  158,    0,  158,  158,
      158,  158,  158,  158,  158,  158,  158,  158,  158,  158,
      158,  158,  158,  158,  158,  158,  158,  158,  158,  158,
      158,  158,  158,  158,  158,  158,  158,  158,  158,  158,
      158,  158,  158,  158,  158,  158,  158,  158,  158,  158,

      158,  158,  158,  158,  158,  158,  158,  158,  158
    } ;

static yyconst flex_int16_t yy_nxt[715] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   20,   20,   20,
       20,   20,   20,   21,   22,   23,   24,   25,   26,   25,
       25,   27,   28,   25,   25,   25,   29,   30,   25,   31,
       25,   25,   25,   32,   33,   25,   25,   34,   35,   36,
       37,   42,   43,   78,   61,   45,  157,   44,   62,   42,
       45,   45,   46,   47,   47,   47,   47,   47,   47,   47,
       48,   48,   42,   45,   68,   51,   52,   42,   42,   49,
       42,   68,   68,   47,   68,   42,   42,  156,  156,   68,
       42,  154,   68,  142,   55,  131,   55,   56,   42,   55,

      158,   55,   56,   45,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   42,  130,  130,  130,  130,   58,
       42,  121,   42,   45,   45,  120,  119,   58,   42,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   71,  110,
       42,   42,  109,   71,   71,   72,   72,  108,   42,   42,
       71,   71,   71,   71,   72,   72,   72,   72,   72,   72,
       72,   72,   72,   72,   45,  107,   75,   75,   75,   75,
       76,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   42,  158,   45,  158,   56,  158,   45,  158,   42,
       45,   86,   45,   86,   56,   81,   45,   99,   98,   97,

       42,   96,  158,   95,   42,   94,   54,   42,   42,   42,
      158,   42,   42,   42,   54,   42,   45,   42,   85,   42,
       45,   42,   91,   91,   91,   91,   91,   91,   91,   92,
       93,   93,  158,   42,  158,   56,   45,   42,   45,   84,
       45,   42,   83,   82,   81,   42,  106,  106,  106,  106,
      106,   80,  158,   42,   79,   42,  158,   42,   67,   45,
      158,   42,   45,   42,   45,   42,  104,  104,  104,  104,
      105,  106,  106,  106,  106,  106,   42,   45,   45,   42,
       45,   42,   45,   45,   42,   66,   65,   42,   64,   42,
      117,  118,   45,   45,   42,   42,   45,   42,   45,   42,

       42,   63,   42,   42,   60,   42,   59,   42,   42,   42,
       42,   45,   38,   42,   38,   42,   38,   42,   42,   40,
       39,   42,   38,   42,  158,  158,  158,  158,   42,  158,
      158,  158,   45,   45,   45,   45,   42,   45,   45,  128,
      128,  128,  129,  130,  130,  130,  130,  130,  130,   42,
       42,   42,   42,   45,   42,   42,   45,   42,   42,   42,
       42,  158,   42,   42,  153,  153,  153,  153,  153,  158,
       42,  158,  158,   42,  158,  158,  158,   45,   42,   45,
       45,   42,   45,   45,  139,  139,  139,  139,  139,  139,
      140,  141,  141,  141,   42,   45,   42,   42,   45,   42,

       42,   45,   42,  158,   42,   42,  158,   42,   42,  158,
       45,   45,   42,   45,  158,   42,  158,  158,   42,  158,
       42,  158,  158,   42,  158,  158,   42,   42,   42,  158,
       42,  158,   45,   45,   45,   42,   42,   45,   42,  151,
      151,  151,  151,  152,  153,  153,  153,  153,  153,   42,
       42,   42,  158,  158,   42,  158,  158,   42,   42,   42,
      158,  158,   42,   41,  158,   41,   50,   50,  158,   50,
       53,   53,  158,   53,   54,   54,   54,   54,   69,   69,
       69,  158,   69,   70,  158,   70,   48,   48,  158,   48,
       73,   73,  158,   73,   74,   74,  158,   74,   87,   87,

       87,  158,   87,   72,   72,   72,   88,   88,  158,   88,
       89,   89,  158,   89,   90,   90,  158,   90,   93,   93,
      158,   93,  100,  100,  158,  100,  101,  101,  158,  101,
      102,  102,  158,  102,  103,  103,  158,  103,  111,  111,
      158,  111,  112,  112,  158,  112,  113,  113,  158,  113,
      114,  114,  158,  114,  115,  115,  158,  115,  116,  116,
      158,  116,  118,  118,  158,  118,  122,  122,  158,  122,
      123,  123,  158,  123,  124,  124,  158,  124,  125,  125,
      158,  125,  126,  126,  158,  126,  127,  127,  158,  127,
      132,  132,  158,  132,  133,  133,  158,  133,  134,  134,

      158,  134,  135,  135,  158,  135,  136,  136,  158,  136,
      137,  137,  158,  137,  138,  138,  158,  138,  141,  141,
      158,  141,  143,  143,  158,  143,  144,  144,  158,  144,
      145,  145,  158,  145,  146,  146,  158,  146,  147,  147,
      158,  147,  148,  148,  158,  148,  149,  149,  158,  149,
      150,  150,  158,  150,  155,  155,  158,  155,  156,  156,
      158,  156,    3,  158,  158,  158,  158,  158,  158,  158,
      158,  158,  158,  158,  158,  158,  158,  158,  158,  158,
      158,  158,  158,  158,  158,  158,  158,  158,  158,  158,
      158,  158,  158,  158,  158,  158,  158,  158,  158,  158,

      158,  158,  158,  158,  158,  158,  158,  158,  158,  158,
      158,  158,  158,  158
    } ;

static yyconst flex_int16_t yy_chk[715] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,   15,   16,  168,   31,   18,  154,   16,   31,   15,
       17,   20,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   18,   19,   41,   19,   19,   17,   20,   17,
       18,   45,   41,   47,   70,   17,   20,  152,  152,   45,
       19,  142,   70,  131,   42,  121,   42,   42,   19,   26,

       47,   26,   26,   48,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   42,  118,  118,  118,  118,   26,
       48,  110,   42,   50,   51,  108,  107,   26,   48,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   99,
       50,   51,   98,   49,   49,   49,   49,   97,   50,   51,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   52,   96,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   53,   53,   53,   53,
       53,   52,   55,   73,   55,   55,   57,   74,   57,   52,
       75,   68,   77,   68,   68,   95,   88,   85,   84,   83,

       73,   82,   55,   80,   74,   79,   57,   75,   73,   77,
       55,   68,   74,   88,   57,   75,   89,   77,   67,   68,
       76,   88,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   86,   89,   86,   86,   90,   76,   91,   65,
      100,   89,   64,   63,   62,   76,   93,   93,   93,   93,
       93,   60,   86,   90,   59,   91,   46,  100,   40,  101,
       86,   90,  102,   91,   92,  100,   92,   92,   92,   92,
       92,   92,   92,   92,   92,   92,  101,  103,  104,  102,
      105,   92,  106,  111,  101,   36,   34,  102,   33,   92,
      105,  105,  112,  113,  103,  104,  114,  105,  115,  106,

      111,   32,  103,  104,   30,  105,   29,  106,  111,  112,
      113,  116,   24,  114,   23,  115,   22,  112,  113,   14,
        8,  114,    7,  115,    3,    0,    0,    0,  116,    0,
        0,    0,  122,  123,  124,  125,  116,  117,  126,  117,
      117,  117,  117,  117,  117,  117,  117,  117,  117,  122,
      123,  124,  125,  127,  117,  126,  128,  122,  123,  124,
      125,    0,  117,  126,  141,  141,  141,  141,  141,    0,
      127,    0,    0,  128,    0,    0,    0,  130,  127,  132,
      133,  128,  129,  134,  129,  129,  129,  129,  129,  129,
      129,  129,  129,  129,  130,  135,  132,  133,  136,  129,

      134,  137,  130,    0,  132,  133,    0,  129,  134,    0,
      138,  139,  135,  143,    0,  136,    0,    0,  137,    0,
      135,    0,    0,  136,    0,    0,  137,  138,  139,    0,
      143,    0,  144,  153,  155,  138,  139,  140,  143,  140,
      140,  140,  140,  140,  140,  140,  140,  140,  140,  144,
      153,  155,    0,    0,  140,    0,    0,  144,  153,  155,
        0,    0,  140,  159,    0,  159,  160,  160,    0,  160,
      161,  161,    0,  161,  162,  162,  162,  162,  163,  163,
      163,    0,  163,  164,    0,  164,  165,  165,    0,  165,
      166,  166,    0,  166,  167,  167,    0,  167,  169,  169,

      169,    0,  169,  170,  170,  170,  171,  171,    0,  171,
      172,  172,    0,  172,  173,  173,    0,  173,  174,  174,
        0,  174,  175,  175,    0,  175,  176,  176,    0,  176,
      177,  177,    0,  177,  178,  178,    0,  178,  179,  179,
        0,  179,  180,  180,    0,  180,  181,  181,    0,  181,
      182,  182,    0,  182,  183,  183,    0,  183,  184,  184,
        0,  184,  185,  185,    0,  185,  186,  186,    0,  186,
      187,  187,    0,  187,  188,  188,    0,  188,  189,  189,
        0,  189,  190,  190,    0,  190,  191,  191,    0,  191,
      192,  192,    0,  192,  193,  193,    0,  193,  194,  194,

        0,  194,  195,  195,    0,  195,  196,  196,    0,  196,
      197,  197,    0,  197,  198,  198,    0,  198,  199,  199,
        0,  199,  200,  200,    0,  200,  201,  201,    0,  201,
      202,  202,    0,  202,  203,  203,    0,  203,  204,  204,
        0,  204,  205,  205,    0,  205,  206,  206,    0,  206,
      207,  207,    0,  207,  208,  208,    0,  208,  209,  209,
        0,  209,  158,  158,  158,  158,  158,  158,  158,  158,
      158,  158,  158,  158,  158,  158,  158,  158,  158,  158,
      158,  158,  158,  158,  158,  158,  158,  158,  158,  158,
      158,  158,  158,  158,  158,  158,  158,  158,  158,  158,

      158,  158,  158,  158,  158,  158,  158,  158,  158,  158,
      158,  158,  158,  158
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[41] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 
    0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexical.l"
#line 3 "lexical.l"
	#include "syntax.tab.h"
	#include "symtable.h"
	//#define debug
	int yycolumn = 1;
  	#define YY_USER_ACTION \
   	yylloc.first_line = yylloc.last_line = yylineno; \
  	yylloc.first_column = yycolumn; \
   	yylloc.last_column = yycolumn + yyleng - 1; \
   	yycolumn += yyleng;
	int lexical_flag = 0;
#line 702 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 37 "lexical.l"

#line 886 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 159 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 663 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 38 "lexical.l"
{char c = input();  while (c != '\n') c = input();}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 39 "lexical.l"
{
	char now = input(); 
	char last = now; 
	while ((now != '/')||(last !='*')) {
		last = now;
		now = input();
		}
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 47 "lexical.l"
{ 	
			#ifdef debug 
			printf("STRUCT\n"); 
			#endif
				yylval.node = (struct TreeNode_ *)malloc(sizeof(Node));
				yylval.node->lineno = yylineno;
				yylval.node->type = 4;
				yylval.node->name = malloc(strlen("STRUCT")+1);
				strcpy(yylval.node->name, "STRUCT");
				yylval.node->child = NULL;
				yylval.node->sibling = NULL;
				return STRUCT;
			}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 60 "lexical.l"
{
			#ifdef debug 
			printf("RETURN\n"); 
			#endif
				yylval.node = (struct TreeNode_ *)malloc(sizeof(Node));
				yylval.node->lineno = yylineno;
				yylval.node->type = 4;
				yylval.node->name = malloc(strlen("RETURN")+1);
				strcpy(yylval.node->name, "RETURN");
				yylval.node->child = NULL;
				yylval.node->sibling = NULL;
				return RETURN;
			}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 73 "lexical.l"
{
	#ifdef debug 
	printf("IF\n"); 
	#endif
				yylval.node = (struct TreeNode_ *)malloc(sizeof(Node));
				yylval.node->lineno = yylineno;
				yylval.node->type = 4;
				yylval.node->name = malloc(strlen("IF")+1);
				strcpy(yylval.node->name, "IF");
				yylval.node->child = NULL;
				yylval.node->sibling = NULL;
				return IF;
			}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 86 "lexical.l"
{
	#ifdef debug 
	printf("ELSE\n"); 
	#endif
				yylval.node = (struct TreeNode_ *)malloc(sizeof(Node));
				yylval.node->lineno = yylineno;
				yylval.node->type = 4;
				yylval.node->name = malloc(strlen("ELSE")+1);
				strcpy(yylval.node->name, "ELSE");
				yylval.node->child = NULL;
				yylval.node->sibling = NULL;
				return ELSE;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 99 "lexical.l"
{
	#ifdef debug 
	printf("WHILE\n"); 
	#endif
				yylval.node = (struct TreeNode_ *)malloc(sizeof(Node));
				yylval.node->lineno = yylineno;
				yylval.node->type = 4;
				yylval.node->name = malloc(strlen("WHILE")+1);
				strcpy(yylval.node->name, "WHILE");
				yylval.node->child = NULL;
				yylval.node->sibling = NULL;
				return WHILE;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 112 "lexical.l"
{
	#ifdef debug 
	printf("TYPE\n"); 
	#endif
				yylval.node = (struct TreeNode_ *)malloc(sizeof(Node));
				yylval.node->lineno = yylineno;
				yylval.node->type = 5;
				yylval.node->name = malloc(strlen(yytext)+1);
				strcpy(yylval.node->name, yytext);
				yylval.node->child = NULL;
				yylval.node->sibling = NULL;
				return TYPE;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 125 "lexical.l"
{
	#ifdef debug 
	printf("ID\n"); 
	#endif
				yylval.node = (struct TreeNode_ *)malloc(sizeof(Node));
				yylval.node->lineno = yylineno;
				yylval.node->type = 1;
				yylval.node->name = malloc(strlen(yytext)+1);
				strcpy(yylval.node->name, yytext);
				yylval.node->child = NULL;
				yylval.node->sibling = NULL;
				return ID;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 138 "lexical.l"
{
	#ifdef debug 
	printf("POINTFLOAT\n"); 
	#endif
				yylval.node = (struct TreeNode_ *)malloc(sizeof(Node));
				yylval.node->lineno = yylineno;
				yylval.node->type = 3;
				yylval.node->type_float = atof(yytext);
				yylval.node->child = NULL;
				yylval.node->sibling = NULL;
				yylval.node->name = malloc(strlen("FLOAT")+1);
				strcpy(yylval.node->name, "FLOAT");
				return FLOAT;
			}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 152 "lexical.l"
{
	#ifdef debug 
	printf("EXPONENTFLOAT\n"); 
	#endif
				yylval.node = (struct TreeNode_ *)malloc(sizeof(Node));
				yylval.node->lineno = yylineno;
				yylval.node->type = 3;
				yylval.node->type_float = atof(yytext);
				yylval.node->child = NULL;
				yylval.node->sibling = NULL;
				yylval.node->name = malloc(strlen("FLOAT")+1);
			 	strcpy(yylval.node->name, "FLOAT");
				return FLOAT;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 165 "lexical.l"
{lexical_flag = 1; printf("Error type A at line %d: Illegal floating point number \'%s\'\n", yylineno, yytext); return FLOAT;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 166 "lexical.l"
{
	#ifdef debug 
	printf("OCTINT\n"); 
	#endif
				yylval.node = (struct TreeNode_ *)malloc(sizeof(Node));
				yylval.node->lineno = yylineno;
				yylval.node->type = 2;
				yylval.node->type_int = strtol(yytext, NULL, 8);
				yylval.node->child = NULL;
				yylval.node->sibling = NULL;
				yylval.node->name = malloc(strlen("OCTINT")+1);
				strcpy(yylval.node->name, "OCTINT");
				return INT;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 179 "lexical.l"
{lexical_flag = 1; printf("Error type A at line %d: Illegal octonary integer \'%s\'\n", yylineno, yytext); return INT;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 180 "lexical.l"
{
	#ifdef debug 
	printf("HEXINT\n"); 
	#endif
				yylval.node = (struct TreeNode_ *)malloc(sizeof(Node));
				yylval.node->lineno = yylineno;
				yylval.node->type = 2;
				yylval.node->type_int = strtol(yytext, NULL, 16);
				yylval.node->child = NULL;
				yylval.node->sibling = NULL;
				yylval.node->name = malloc(strlen("HEXINT")+1);
				strcpy(yylval.node->name, "HEXINT");
				return INT;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 193 "lexical.l"
{lexical_flag = 1; printf("Error type A at line %d: Illegal hexadecimal integer \'%s\'\n", yylineno, yytext); return INT;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 194 "lexical.l"
{
	#ifdef debug 
	printf("DECINT\n"); 
	#endif
				yylval.node = (struct TreeNode_ *)malloc(sizeof(Node));
				yylval.node->lineno = yylineno;
				yylval.node->type = 2;
				yylval.node->type_int = atoi(yytext);
				yylval.node->child = NULL;
				yylval.node->sibling = NULL;
				yylval.node->name = malloc(strlen("INT")+1);
				strcpy(yylval.node->name, "INT");
				return INT;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 207 "lexical.l"
{lexical_flag = 1; printf("Error type A at line %d: Illegal decimal integer \'%s\'\n", yylineno, yytext); return INT;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 208 "lexical.l"
{
	#ifdef debug 
	printf("SEMI\n"); 
	#endif
			yylval.node = (struct TreeNode_ *)malloc(sizeof(Node));
			yylval.node->lineno = yylineno;
			yylval.node->type = 4;
			yylval.node->child = NULL;
			yylval.node->sibling = NULL;
			yylval.node->name = malloc(strlen("SEMI")+1);
			strcpy(yylval.node->name, "SEMI");
			return SEMI;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 220 "lexical.l"
{
	#ifdef debug 
	printf("COMMA\n"); 
	#endif
			yylval.node = (struct TreeNode_ *)malloc(sizeof(Node));
			yylval.node->lineno = yylineno;
			yylval.node->type = 4;
			yylval.node->child = NULL;
			yylval.node->sibling = NULL;
			yylval.node->name = malloc(strlen("COMMA")+1);
			strcpy(yylval.node->name, "COMMA");
			return COMMA;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 232 "lexical.l"
{
	#ifdef debug 
	printf("ASSIGNOP\n"); 
	#endif
			yylval.node = (struct TreeNode_ *)malloc(sizeof(Node));
			yylval.node->lineno = yylineno;
			yylval.node->type = 4;
			yylval.node->child = NULL;
			yylval.node->sibling = NULL;
			yylval.node->name = malloc(strlen("ASSIGNOP")+1);
			strcpy(yylval.node->name, "ASSIGNOP");
			return ASSIGNOP;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 244 "lexical.l"
{
	#ifdef debug 
	printf("RELOP\n"); 
	#endif
			yylval.node = (struct TreeNode_ *)malloc(sizeof(Node));
			yylval.node->lineno = yylineno;
			yylval.node->type = 4;
			yylval.node->child = NULL;
			yylval.node->sibling = NULL;
			yylval.node->name = malloc(strlen("RELOP")+1);
			strcpy(yylval.node->name, "RELOP");
			return RELOP;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 256 "lexical.l"
{
	#ifdef debug 
	printf("PLUS\n"); 
	#endif
			yylval.node = (struct TreeNode_ *)malloc(sizeof(Node));
			yylval.node->lineno = yylineno;
			yylval.node->type = 4;
			yylval.node->name = malloc(strlen("PLUS")+1);
			strcpy(yylval.node->name, "PLUS");
			return PLUS;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 266 "lexical.l"
{
	#ifdef debug 
	printf("MINUS\n"); 
	#endif
			yylval.node = (struct TreeNode_ *)malloc(sizeof(Node));
			yylval.node->lineno = yylineno;
			yylval.node->type = 4;
			yylval.node->child = NULL;
			yylval.node->sibling = NULL;
			yylval.node->name = malloc(strlen("MINUS")+1);
			strcpy(yylval.node->name, "MINUS");
			return MINUS;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 278 "lexical.l"
{
	#ifdef debug 
	printf("STAR\n"); 
	#endif
			yylval.node = (struct TreeNode_ *)malloc(sizeof(Node));
			yylval.node->lineno = yylineno;
			yylval.node->type = 4;
			yylval.node->child = NULL;
			yylval.node->sibling = NULL;
			yylval.node->name = malloc(strlen("STAR")+1);
			strcpy(yylval.node->name, "STAR");
			return STAR;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 290 "lexical.l"
{
	#ifdef debug 
	printf("AND\n"); 
	#endif
			yylval.node = (struct TreeNode_ *)malloc(sizeof(Node));
			yylval.node->lineno = yylineno;
			yylval.node->type = 4;
			yylval.node->child = NULL;
			yylval.node->sibling = NULL;
			yylval.node->name = malloc(strlen("AND")+1);
			strcpy(yylval.node->name, "AND");
			return AND;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 302 "lexical.l"
{
	#ifdef debug 
	printf("OR\n"); 
	#endif
			yylval.node = (struct TreeNode_ *)malloc(sizeof(Node));
			yylval.node->lineno = yylineno;
			yylval.node->type = 4;
			yylval.node->child = NULL;
			yylval.node->sibling = NULL;
			yylval.node->name = malloc(strlen("OR")+1);
			strcpy(yylval.node->name, "OR");
			return OR;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 314 "lexical.l"
{
	#ifdef debug 
	printf("DOT\n"); 
	#endif
			yylval.node = (struct TreeNode_ *)malloc(sizeof(Node));
			yylval.node->lineno = yylineno;
			yylval.node->type = 4;
			yylval.node->child = NULL;
			yylval.node->sibling = NULL;
			yylval.node->name = malloc(strlen("DOT")+1);
			strcpy(yylval.node->name, "DOT");
			return DOT;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 326 "lexical.l"
{
	#ifdef debug 
	printf("NOT\n"); 
	#endif
			yylval.node = (struct TreeNode_ *)malloc(sizeof(Node));
			yylval.node->lineno = yylineno;
			yylval.node->type = 4;
			yylval.node->child = NULL;
			yylval.node->sibling = NULL;
			yylval.node->name = malloc(strlen("NOT")+1);
			strcpy(yylval.node->name, "NOT");
			return NOT;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 338 "lexical.l"
{
	#ifdef debug 
	printf("LP\n"); 
	#endif
			yylval.node = (struct TreeNode_ *)malloc(sizeof(Node));
			yylval.node->lineno = yylineno;
			yylval.node->type = 4;
			yylval.node->name = malloc(strlen("LP")+1);
			strcpy(yylval.node->name, "LP");
			return LP;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 348 "lexical.l"
{
	#ifdef debug 
	printf("RP\n"); 
	#endif
			yylval.node = (struct TreeNode_ *)malloc(sizeof(Node));
			yylval.node->lineno = yylineno;
			yylval.node->type = 4;
			yylval.node->child = NULL;
			yylval.node->sibling = NULL;
			yylval.node->name = malloc(strlen("RP")+1);
			strcpy(yylval.node->name, "RP");
			return RP;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 360 "lexical.l"
{
	#ifdef debug 
	printf("LB\n"); 
	#endif
			yylval.node = (struct TreeNode_ *)malloc(sizeof(Node));
			yylval.node->lineno = yylineno;
			yylval.node->type = 4;
			yylval.node->child = NULL;
			yylval.node->sibling = NULL;
			yylval.node->name = malloc(strlen("LB")+1);
			strcpy(yylval.node->name, "LB");
			return LB;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 372 "lexical.l"
{
	#ifdef debug 
	printf("RB\n"); 
	#endif
			yylval.node = (struct TreeNode_ *)malloc(sizeof(Node));
			yylval.node->lineno = yylineno;
			yylval.node->type = 4;
			yylval.node->child = NULL;
			yylval.node->sibling = NULL;
			yylval.node->name = malloc(strlen("RB")+1);
			strcpy(yylval.node->name, "RB");
			return RB;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 384 "lexical.l"
{
	#ifdef debug 
	printf("LC\n"); 
	#endif
			yylval.node = (struct TreeNode_ *)malloc(sizeof(Node));
			yylval.node->lineno = yylineno;
			yylval.node->type = 4;
			yylval.node->child = NULL;
			yylval.node->sibling = NULL;
			yylval.node->name = malloc(strlen("LC")+1);
			strcpy(yylval.node->name, "LC");
			return LC;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 396 "lexical.l"
{
	#ifdef debug 
	printf("RC\n"); 
	#endif
			yylval.node = (struct TreeNode_ *)malloc(sizeof(Node));
			yylval.node->lineno = yylineno;
			yylval.node->type = 4;
			yylval.node->child = NULL;
			yylval.node->sibling = NULL;
			yylval.node->name = malloc(strlen("RC")+1);
			strcpy(yylval.node->name, "RC");
			return RC;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 408 "lexical.l"
{printf("");}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 409 "lexical.l"
{
	#ifdef debug 
	printf("DIV\n"); 
	#endif
			yylval.node = (struct TreeNode_ *)malloc(sizeof(Node));
			yylval.node->lineno = yylineno;
			yylval.node->type = 4;
			yylval.node->child = NULL;
			yylval.node->sibling = NULL;
			yylval.node->name = malloc(strlen("DIV")+1);
			strcpy(yylval.node->name, "DIV");
			return DIV;}
	YY_BREAK
case 38:
/* rule 38 can match eol */
YY_RULE_SETUP
#line 421 "lexical.l"
{yycolumn = 1; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 422 "lexical.l"
{ lexical_flag = 1; printf("Error type A at line %d: Mysterious characters \'%s\'\n", yylineno, yytext);}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 423 "lexical.l"
ECHO;
	YY_BREAK
#line 1526 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 159 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 159 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 158);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 423 "lexical.l"


